### PR TITLE
Nf mblink2

### PR DESCRIPTION
**Pull request by nikolaif399**
- Add MBLink converter node
- Updated gazebo to output our contact force message (this is basically broken, I set up another issue to fix this)

### CODE REVIEW

**Comment by nikolaif399** [comment]
MBLink converter is done but not tested yet, simulator is updated

**Review by jcnorby — COMMENTED** [review]
Mostly looks fine, although you should delete all the build folders in SpiritSDK, we don't want to add those to source.

**Comment by nikolaif399** [comment]
Thought I already did? That must not have gotten pushed up. Will resubmit.

**Comment by nikolaif399** [comment]
Actually all of those build folders ship with the SpiritSDK source. For now let's just leave them in, if we need to prune things later we can just extract mblink stuff from the SDK directly and discard the rest

**Review by jcnorby — APPROVED** [review]

**Comment by jcnorby** [comment]
I'd like to do that at some point, adding 355k lines of code just to get mblink to work seems overkill.

**Comment by nikolaif399** [comment]
Will make that a separate issue. I anticipate being a little bored over winter break, will get to these bookkeeping things around then.

**Pull request merged**
