### PR TITLE
Ardalan dev

### PR DESCRIPTION
**Pull request by ardalantj**
Added demo figures for logging package. Added some comments, will add more.

### CODE REVIEW

**Comment by jcnorby** [comment]
I just merged in another PR, you'll need to merge main on this branch and re-push

**Comment by ardalantj** [comment]
> I just merged in another PR, you'll need to merge main on this branch and re-push

Just did.

**Comment by jcnorby** [comment]
Did you push them? Github says the branch is still out of date.

**Comment by ardalantj** [comment]
> Did you push them? Github says the branch is still out of date.

Yeah when I do it again it says everything up to date !

**Comment by nikolaif399** [comment]
Looks like there are merge conflicts, might have to work through those first

**Review by jcnorby — APPROVED** [review]

**Pull request merged**
